<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <UserSecretsId>874fc08e-b418-4cd2-b81b-ecb54e4922cd</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenTelemetry" Version="1.14.0" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
      <PackageReference Include="Sentry" Version="5.16.2" />
      <PackageReference Include="Sentry.AspNetCore" Version="5.16.2" />
      <PackageReference Include="Sentry.OpenTelemetry" Version="5.16.2" />
    </ItemGroup>

</Project>
